---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2019/4/23 9:34
---

base = base or {}

--- 判断值是否存在于表中
--- @param value any
--- @param tab table
function base.is_include(value, tab)
    for _, v in ipairs(tab) do
        if v == value then
            return true
        end
    end
    return false
end

function base.getRandomValueInList(list)
    local rand = base.random_int(1, #list)
    return list[rand]
end

--- 获取哈希表中随机的键
--- @generic K, V 表的键和值
--- @param tab table<K, V>
--- @return K
function base.getRandomKey(tab)
    local temp = {}
    for k, _ in pairs(tab) do
        table.insert(temp, k)
    end
    return base.getRandomValueInList(temp)
end

--- 获取哈希表中所有的键
--- @generic K, V 表的键和值
--- @param tab table<K, V>
--- @return table<number, K>
function table.keys(tab)
    local keys = {}
    for k, _ in pairs(tab) do
        table.insert(keys, k)
    end
    return keys
end