---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2019/4/16 10:46
---

local base = {}
--- 根据掉落表获取随机掉落的物品ID
--- @param drop_table table<string|table, number> 掉落表
--- @return number 物品ID
function base.getRandomDropFromTable(drop_table)
    local total = 100
    for id, possibility in pairs(drop_table) do
        if (math.random(0, total) < possibility) then
            if type(id) == 'string' then
                return id
            elseif type(id) == 'table' then
                return base.getRandomDropFromTable(id)
            end
        end
        total = total - possibility
    end
    return 0
end

function base.random_int(m, n)
    return math.random(m, n)
end

function base.getRandomValueInList(list)
    local rand = base.random_int(1, #list)
    return list[rand]
end

--- 获取哈希表中随机的键
--- @generic K, V 表的键和值
--- @param tab table<K, V>
--- @return K
function base.getRandomKey(tab)
    local temp = {}
    for k, _ in pairs(tab) do
        table.insert(temp, k)
    end
    return base.getRandomValueInList(temp)
end

local attr = {
    wuxing = '悟性',
    gengu = '根骨',
    fuyuan = '福缘',
    yishu = '医术',
    danpo = '胆魄',
    jingmai = '经脉'
}

print(base.getRandomKey(attr))